title: Youth Opportunities
description: Discover amazing opportunities for university students and graduates
baseurl: ""
url: "https://youthopps.org"
analytics_id: "G-MGW77TH5Z3"
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - docs
  - Gemfile
  - Gemfile.lock
